#!/usr/bin/env python3
"""
gen_catalog.py — Battle Skills catalog generator
Auto-generates skills_index.json and CATALOG.md from skills/ directory.

Usage:
    python3 scripts/gen_catalog.py
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

# ── Config ─────────────────────────────────────────────────────────────────────
REPO_ROOT      = Path(__file__).parent.parent
SKILLS_DIR     = REPO_ROOT / "skills"
INDEX_OUTPUT   = REPO_ROOT / "skills_index.json"
CATALOG_OUTPUT = REPO_ROOT / "CATALOG.md"

GREEN = "\033[92m"
CYAN  = "\033[96m"
RESET = "\033[0m"
BOLD  = "\033[1m"


# ── Helpers ────────────────────────────────────────────────────────────────────

def parse_frontmatter(text: str) -> dict:
    fm: dict = {}
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            for line in parts[1].strip().splitlines():
                if ":" in line:
                    key, _, val = line.partition(":")
                    raw = val.strip()
                    # parse list fields
                    if raw.startswith("["):
                        items = [i.strip().strip("'\"") for i in raw.strip("[]").split(",") if i.strip()]
                        fm[key.strip()] = items
                    else:
                        fm[key.strip()] = raw
    return fm


def parse_skills() -> list[dict]:
    skills = []
    if not SKILLS_DIR.exists():
        return skills

    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue

        content = skill_md.read_text(encoding="utf-8")
        fm      = parse_frontmatter(content)

        # count lines in SKILL.md body
        lines = len(content.splitlines())

        # detect bundled resources
        has_references = (skill_dir / "references").exists()
        has_scripts    = (skill_dir / "scripts").exists()
        has_assets     = (skill_dir / "assets").exists()

        skills.append({
            "name":        fm.get("name", skill_dir.name),
            "description": fm.get("description", ""),
            "tags":        fm.get("tags", []),
            "tools":       fm.get("tools", []),
            "version":     fm.get("version", ""),
            "author":      fm.get("author", ""),
            "path":        f"skills/{skill_dir.name}",
            "lines":       lines,
            "has_references": has_references,
            "has_scripts":    has_scripts,
            "has_assets":     has_assets,
        })

    return skills


def write_index(skills: list[dict]) -> None:
    index = {
        "total":        len(skills),
        "skills":       skills,
    }
    INDEX_OUTPUT.write_text(json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  {GREEN}✓{RESET} {INDEX_OUTPUT.relative_to(REPO_ROOT)}")


def write_catalog(skills: list[dict]) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        "# ⚔ Battle Skills — Catalog",
        "",
        f"> Auto-generated on {now}. Do not edit manually — run `python3 scripts/gen_catalog.py`.",
        "",
        f"**Total skills: {len(skills)}**",
        "",
        "| Skill | Description | Tags | Tools |",
        "|-------|-------------|------|-------|",
    ]

    for s in skills:
        name        = s["name"]
        path        = s["path"]
        description = s["description"][:90] + "…" if len(s["description"]) > 90 else s["description"]
        tags        = ", ".join(s["tags"]) if isinstance(s["tags"], list) else s["tags"]
        tools       = ", ".join(s["tools"]) if isinstance(s["tools"], list) else s["tools"]
        lines.append(f"| [{name}]({path}/SKILL.md) | {description} | {tags} | {tools} |")

    lines += [
        "",
        "---",
        "",
        "_Generated by [gen_catalog.py](scripts/gen_catalog.py)_",
        "",
    ]

    CATALOG_OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"  {GREEN}✓{RESET} {CATALOG_OUTPUT.relative_to(REPO_ROOT)}")


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print(f"\n{BOLD}{CYAN}⚔  Battle Skills — Catalog Generator{RESET}\n")

    skills = parse_skills()
    print(f"  Found {len(skills)} skill(s)\n")

    write_index(skills)
    write_catalog(skills)

    print(f"\n{GREEN}Done!{RESET} Catalog updated with {len(skills)} skill(s).\n")


if __name__ == "__main__":
    main()
